services:
  - type: web
    name: dentoclinic
    env: python
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dental.wsgi:application
    plan: free
    region: oregon
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: dental.settings
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: SECRET_KEY
        generateValue: true 